Category:
  connection: doctrine
  tableName: category
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    title:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
    gallery_id:
      type: integer(8)
      notnull: true
      primary: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
Gallery:
  connection: doctrine
  tableName: gallery
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    title:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
Image:
  connection: doctrine
  tableName: image
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    title:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
    filepath:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
    category_id:
      type: integer(8)
      notnull: true
      primary: false
      autoincrement: false
    comment:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      notnull: true
      primary: false
      autoincrement: false
