//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3074
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace MyLiveMesh.UserDirectoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="UserDirectoryServiceReference.UserDirectory")]
    public interface UserDirectory {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserDirectory/CreateDirectoryOnServer", ReplyAction="urn:UserDirectory/CreateDirectoryOnServerResponse")]
        System.IAsyncResult BeginCreateDirectoryOnServer(string path, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateDirectoryOnServer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface UserDirectoryChannel : MyLiveMesh.UserDirectoryServiceReference.UserDirectory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CreateDirectoryOnServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateDirectoryOnServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UserDirectoryClient : System.ServiceModel.ClientBase<MyLiveMesh.UserDirectoryServiceReference.UserDirectory>, MyLiveMesh.UserDirectoryServiceReference.UserDirectory {
        
        private BeginOperationDelegate onBeginCreateDirectoryOnServerDelegate;
        
        private EndOperationDelegate onEndCreateDirectoryOnServerDelegate;
        
        private System.Threading.SendOrPostCallback onCreateDirectoryOnServerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UserDirectoryClient() {
        }
        
        public UserDirectoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserDirectoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserDirectoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserDirectoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CreateDirectoryOnServerCompletedEventArgs> CreateDirectoryOnServerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyLiveMesh.UserDirectoryServiceReference.UserDirectory.BeginCreateDirectoryOnServer(string path, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateDirectoryOnServer(path, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool MyLiveMesh.UserDirectoryServiceReference.UserDirectory.EndCreateDirectoryOnServer(System.IAsyncResult result) {
            return base.Channel.EndCreateDirectoryOnServer(result);
        }
        
        private System.IAsyncResult OnBeginCreateDirectoryOnServer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            return ((MyLiveMesh.UserDirectoryServiceReference.UserDirectory)(this)).BeginCreateDirectoryOnServer(path, callback, asyncState);
        }
        
        private object[] OnEndCreateDirectoryOnServer(System.IAsyncResult result) {
            bool retVal = ((MyLiveMesh.UserDirectoryServiceReference.UserDirectory)(this)).EndCreateDirectoryOnServer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateDirectoryOnServerCompleted(object state) {
            if ((this.CreateDirectoryOnServerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateDirectoryOnServerCompleted(this, new CreateDirectoryOnServerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateDirectoryOnServerAsync(string path) {
            this.CreateDirectoryOnServerAsync(path, null);
        }
        
        public void CreateDirectoryOnServerAsync(string path, object userState) {
            if ((this.onBeginCreateDirectoryOnServerDelegate == null)) {
                this.onBeginCreateDirectoryOnServerDelegate = new BeginOperationDelegate(this.OnBeginCreateDirectoryOnServer);
            }
            if ((this.onEndCreateDirectoryOnServerDelegate == null)) {
                this.onEndCreateDirectoryOnServerDelegate = new EndOperationDelegate(this.OnEndCreateDirectoryOnServer);
            }
            if ((this.onCreateDirectoryOnServerCompletedDelegate == null)) {
                this.onCreateDirectoryOnServerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateDirectoryOnServerCompleted);
            }
            base.InvokeAsync(this.onBeginCreateDirectoryOnServerDelegate, new object[] {
                        path}, this.onEndCreateDirectoryOnServerDelegate, this.onCreateDirectoryOnServerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MyLiveMesh.UserDirectoryServiceReference.UserDirectory CreateChannel() {
            return new UserDirectoryClientChannel(this);
        }
        
        private class UserDirectoryClientChannel : ChannelBase<MyLiveMesh.UserDirectoryServiceReference.UserDirectory>, MyLiveMesh.UserDirectoryServiceReference.UserDirectory {
            
            public UserDirectoryClientChannel(System.ServiceModel.ClientBase<MyLiveMesh.UserDirectoryServiceReference.UserDirectory> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCreateDirectoryOnServer(string path, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = path;
                System.IAsyncResult _result = base.BeginInvoke("CreateDirectoryOnServer", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateDirectoryOnServer(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateDirectoryOnServer", _args, result)));
                return _result;
            }
        }
    }
}
