<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/10/12 12:15:22
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basecategoryformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/base/BaseCategoryFormFilter.class.php',
  'basegalleryformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/base/BaseGalleryFormFilter.class.php',
  'baseimageformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/base/BaseImageFormFilter.class.php',
  'baseformfilterdoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'categoryformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/CategoryFormFilter.class.php',
  'galleryformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/GalleryFormFilter.class.php',
  'imageformfilter' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/filter/doctrine/ImageFormFilter.class.php',
  'baseform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/BaseForm.class.php',
  'basecategoryform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/base/BaseCategoryForm.class.php',
  'basegalleryform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/base/BaseGalleryForm.class.php',
  'baseimageform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/base/BaseImageForm.class.php',
  'baseformdoctrine' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/BaseFormDoctrine.class.php',
  'categoryform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/CategoryForm.class.php',
  'galleryform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/GalleryForm.class.php',
  'imageform' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/form/doctrine/ImageForm.class.php',

  // project_model
  'basecategory' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/base/BaseCategory.class.php',
  'basegallery' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/base/BaseGallery.class.php',
  'baseimage' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/base/BaseImage.class.php',
  'category' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/Category.class.php',
  'categorytable' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/CategoryTable.class.php',
  'gallery' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/Gallery.class.php',
  'gallerytable' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/GalleryTable.class.php',
  'image' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/Image.class.php',
  'imagetable' => 'E:/dev/epitaf/as-gallery/branches/symfony/lib/model/doctrine/ImageTable.class.php',

  // application
  'myuser' => 'E:/dev/epitaf/as-gallery/branches/symfony/apps/frontend/lib/myUser.class.php',

  // modules
);
