<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/12 12:15:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:E:\\dev\\epitaf\\as-gallery\\branches\\symfony/data/fromScratch.db',
  'name' => 'doctrine',
)),);
