
typedef struct s_sysinfo
{
  int   nbargs;
  char  *sysname;
  char  argtype[8][128];
  char	argname[8][128];
  char  *return_type;
}t_sysinfo;

t_sysinfo       SYSINFO[483] =
  {
    {1, "syscall", {"int"}, {"anom"}, "int"},
    {1, "exit", {"int"}, {"rval"}, "void"},
    {0, "fork", {""}, {""}, "int"},
    {3, "read", {"int", "void *", "size_t"}, {"fd", "buf", "nbyte"}, "int"},
    {3, "write", {"int", "const void *", "size_t"}, {"fd", "buf", "nbyte"}, "int"},
    {3, "open", {"char *", "int", "int"}, {"path", "flags", "mode"}, "int"},
    {1, "close", {"int"}, {"fd"}, "int"},
    {0, "wait4", {""}, {""}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "link", {"char *", "char *"}, {"path", "link"}, "int"},
    {1, "unlink", {"char *"}, {"path"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "chdir", {"char *"}, {"path"}, "int"},
    {1, "fchdir", {"int"}, {"fd"}, "int"},
    {3, "mknod", {"char *", "int", "int"}, {"path", "mode", "dev"}, "int"},
    {2, "chmod", {"char *", "int"}, {"path", "mode"}, "int"},
    {3, "chown", {"char *", "int", "int"}, {"path", "uid", "gid"}, "int"},
    {1, "break", {"unknow"}, {"unknow"}, "int"},
    {3, "freebsd4_getfsstat", {"struct ostatfs *", "long", "int"}, {"buf", "bufsize", "flags"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, "getpid", {""}, {""}, "int"},
    {4, "mount", {"char *", "char *", "int", "caddr_t"}, {"type", "path", "flags", "data"}, "int"},
    {2, "unmount", {"char *", "int"}, {"path", "flags"}, "int"},
    {1, "setuid", {"uid_t"}, {"uid"}, "int"},
    {0, "getuid", {""}, {""}, "int"},
    {0, "geteuid", {""}, {""}, "int"},
    {4, "ptrace", {"int", "pid_t", "caddr_t", "int"}, {"req", "pid", "addr", "data"}, "int"},
    {3, "recvmsg", {"int", "struct msghdr *", "int"}, {"s", "msg", "flags"}, "int"},
    {3, "sendmsg", {"int", "struct msghdr *", "int"}, {"s", "msg", "flags"}, "int"},
    {6, "recvfrom", {"int", "caddr_t", "size_t", "int", "struct sockaddr *__restrict", "__socklen_t *__restrict"}, {"s", "buf", "len", "flags", "from", "fromlenaddr"}, "int"},
    {3, "accept", {"int", "struct sockaddr *__restrict", "__socklen_t *__restrict"}, {"s", "name", "anamelen"}, "int"},
    {3, "getpeername", {"int", "struct sockaddr *__restrict", "__socklen_t *__restrict"}, {"fdes", "asa", "alen"}, "int"},
    {3, "getsockname", {"int", "struct sockaddr *__restrict", "__socklen_t *__restrict"}, {"fdes", "asa", "alen"}, "int"},
    {2, "access", {"char *", "int"}, {"path", "flags"}, "int"},
    {2, "chflags", {"char *", "int"}, {"path", "flags"}, "int"},
    {2, "fchflags", {"int", "int"}, {"fd", "flags"}, "int"},
    {0, "sync", {""}, {""}, "int"},
    {2, "kill", {"int", "int"}, {"pid", "signum"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, "getppid", {""}, {""}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "dup", {"u_int"}, {"fd"}, "int"},
    {0, "pipe", {""}, {""}, "int"},
    {0, "getegid", {""}, {""}, "int"},
    {4, "profil", {"caddr_t", "size_t", "size_t", "u_int"}, {"samples", "size", "offset", "scale"}, "int"},
    {4, "ktrace", {"const char *", "int", "int", "int"}, {"fname", "ops", "facs", "pid"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, "getgid", {""}, {""}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "getlogin", {"char *", "u_int"}, {"namebuf", "namelen"}, "int"},
    {1, "setlogin", {"char *"}, {"namebuf"}, "int"},
    {1, "acct", {"char *"}, {"path"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "sigaltstack", {"stack_t *", "stack_t *"}, {"ss", "oss"}, "int"},
    {3, "ioctl", {"int", "u_long", "caddr_t"}, {"fd", "com", "data"}, "int"},
    {1, "reboot", {"int"}, {"opt"}, "int"},
    {1, "revoke", {"char *"}, {"path"}, "int"},
    {2, "symlink", {"char *", "char *"}, {"path", "link"}, "int"},
    {3, "readlink", {"char *", "char *", "int"}, {"path", "buf", "count"}, "int"},
    {3, "execve", {"char *", "char **", "char **"}, {"fname", "argv", "envv"}, "int"},
    {1, "umask", {"int"}, {"newmask"}, "int"},
    {1, "chroot", {"char *"}, {"path"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {3, "msync", {"void *", "size_t", "int"}, {"addr", "len", "flags"}, "int"},
    {0, "vfork", {""}, {""}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {1, "sbrk", {"int"}, {"incr"}, "int"},
    {1, "sstk", {"int"}, {"incr"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "vadvise", {"int"}, {"anom"}, "int"},
    {2, "munmap", {"void *", "size_t"}, {"addr", "len"}, "int"},
    {3, "mprotect", {"const void *", "size_t", "int"}, {"addr", "len", "prot"}, "int"},
    {3, "madvise", {"void *", "size_t", "int"}, {"addr", "len", "behav"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {3, "mincore", {"const void *", "size_t", "char *"}, {"addr", "len", "vec"}, "int"},
    {2, "getgroups", {"u_int", "gid_t *"}, {"gidsetsize", "gidset"}, "int"},
    {2, "setgroups", {"u_int", "gid_t *"}, {"gidsetsize", "gidset"}, "int"},
    {0, "getpgrp", {""}, {""}, "int"},
    {2, "setpgid", {"int", "int"}, {"pid", "pgid"}, "int"},
    {3, "setitimer", {"u_int", "struct itimerval *", "struct itimerval *"}, {"which", "itv", "oitv"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "swapon", {"char *"}, {"name"}, "int"},
    {2, "getitimer", {"u_int", "struct itimerval *"}, {"which", "itv"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, "getdtablesize", {""}, {""}, "int"},
    {2, "dup2", {"u_int", "u_int"}, {"from", "to"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "fcntl", {"int", "int", "long"}, {"fd", "cmd", "arg"}, "int"},
    {5, "select", {"int", "fd_set *", "fd_set *", "fd_set *", "struct timeval *"}, {"nd", "in", "ou", "ex", "tv"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "fsync", {"int"}, {"fd"}, "int"},
    {3, "setpriority", {"int", "int", "int"}, {"which", "who", "prio"}, "int"},
    {3, "socket", {"int", "int", "int"}, {"domain", "type", "protocol"}, "int"},
    {3, "connect", {"int", "caddr_t", "int"}, {"s", "name", "namelen"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "getpriority", {"int", "int"}, {"which", "who"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {3, "bind", {"int", "caddr_t", "int"}, {"s", "name", "namelen"}, "int"},
    {5, "setsockopt", {"int", "int", "int", "caddr_t", "int"}, {"s", "level", "name", "val", "valsize"}, "int"},
    {2, "listen", {"int", "int"}, {"s", "backlog"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "gettimeofday", {"struct timeval *", "struct timezone *"}, {"tp", "tzp"}, "int"},
    {2, "getrusage", {"int", "struct rusage *"}, {"who", "rusage"}, "int"},
    {5, "getsockopt", {"int", "int", "int", "caddr_t", "int *"}, {"s", "level", "name", "val", "avalsize"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "readv", {"int", "struct iovec *", "u_int"}, {"fd", "iovp", "iovcnt"}, "int"},
    {3, "writev", {"int", "struct iovec *", "u_int"}, {"fd", "iovp", "iovcnt"}, "int"},
    {2, "settimeofday", {"struct timeval *", "struct timezone *"}, {"tv", "tzp"}, "int"},
    {3, "fchown", {"int", "int", "int"}, {"fd", "uid", "gid"}, "int"},
    {2, "fchmod", {"int", "int"}, {"fd", "mode"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "setreuid", {"int", "int"}, {"ruid", "euid"}, "int"},
    {2, "setregid", {"int", "int"}, {"rgid", "egid"}, "int"},
    {2, "rename", {"char *", "char *"}, {"from", "to"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "flock", {"int", "int"}, {"fd", "how"}, "int"},
    {2, "mkfifo", {"char *", "int"}, {"path", "mode"}, "int"},
    {6, "sendto", {"int", "caddr_t", "size_t", "int", "caddr_t", "int"}, {"s", "buf", "len", "flags", "to", "tolen"}, "int"},
    {2, "shutdown", {"int", "int"}, {"s", "how"}, "int"},
    {4, "socketpair", {"int", "int", "int", "int *"}, {"domain", "type", "protocol", "rsv"}, "int"},
    {2, "mkdir", {"char *", "int"}, {"path", "mode"}, "int"},
    {1, "rmdir", {"char *"}, {"path"}, "int"},
    {2, "utimes", {"char *", "struct timeval *"}, {"path", "tptr"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "adjtime", {"struct timeval *", "struct timeval *"}, {"delta", "olddelta"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, "setsid", {""}, {""}, "int"},
    {4, "quotactl", {"char *", "int", "int", "caddr_t"}, {"path", "cmd", "uid", "arg"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "nfssvc", {"int", "caddr_t"}, {"flag", "argp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "freebsd4_statfs", {"char *", "struct ostatfs *"}, {"path", "buf"}, "int"},
    {2, "freebsd4_fstatfs", {"int", "struct ostatfs *"}, {"fd", "buf"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "lgetfh", {"char *", "struct fhandle *"}, {"fname", "fhp"}, "int"},
    {2, "getfh", {"char *", "struct fhandle *"}, {"fname", "fhp"}, "int"},
    {2, "getdomainname", {"char *", "int"}, {"domainname", "len"}, "int"},
    {2, "setdomainname", {"char *", "int"}, {"domainname", "len"}, "int"},
    {1, "uname", {"struct utsname *"}, {"name"}, "int"},
    {2, "sysarch", {"int", "char *"}, {"op", "parms"}, "int"},
    {3, "rtprio", {"int", "pid_t", "struct rtprio *"}, {"function", "pid", "rtp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {5, "semsys", {"int", "int", "int", "int", "int"}, {"which", "a2", "a3", "a4", "a5"}, "int"},
    {6, "msgsys", {"int", "int", "int", "int", "int", "int"}, {"which", "a2", "a3", "a4", "a5", "a6"}, "int"},
    {4, "shmsys", {"int", "int", "int", "int"}, {"which", "a2", "a3", "a4"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {5, "freebsd6_pread", {"int", "void *", "size_t", "int", "off_t"}, {"fd", "buf", "nbyte", "pad", "offset"}, "int"},
    {5, "freebsd6_pwrite", {"int", "const void *", "size_t", "int", "off_t"}, {"fd", "buf", "nbyte", "pad", "offset"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "ntp_adjtime", {"struct timex *"}, {"tp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {1, "setgid", {"gid_t"}, {"gid"}, "int"},
    {1, "setegid", {"gid_t"}, {"egid"}, "int"},
    {1, "seteuid", {"uid_t"}, {"euid"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "stat", {"char *", "struct stat *"}, {"path", "ub"}, "int"},
    {2, "fstat", {"int", "struct stat *"}, {"fd", "sb"}, "int"},
    {2, "lstat", {"char *", "struct stat *"}, {"path", "ub"}, "int"},
    {2, "pathconf", {"char *", "int"}, {"path", "name"}, "int"},
    {2, "fpathconf", {"int", "int"}, {"fd", "name"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, "getrlimit", {""}, {""}, "int"},
    {0, "setrlimit", {""}, {""}, "int"},
    {4, "getdirentries", {"int", "char *", "u_int", "long *"}, {"fd", "buf", "count", "basep"}, "int"},
    {7, "freebsd6_mmap", {"caddr_t", "size_t", "int", "int", "int", "int", "off_t"}, {"addr", "len", "prot", "flags", "fd", "pad", "pos"}, "int"},
    {1, "__syscall", {"int"}, {"anom"}, "int"},
    {4, "freebsd6_lseek", {"int", "int", "off_t", "int"}, {"fd", "pad", "offset", "whence"}, "int"},
    {3, "freebsd6_truncate", {"char *", "int", "off_t"}, {"path", "pad", "length"}, "int"},
    {3, "freebsd6_ftruncate", {"int", "int", "off_t"}, {"fd", "pad", "length"}, "int"},
    {0, "__sysctl", {""}, {""}, "int"},
    {2, "mlock", {"const void *", "size_t"}, {"addr", "len"}, "int"},
    {2, "munlock", {"const void *", "size_t"}, {"addr", "len"}, "int"},
    {1, "undelete", {"char *"}, {"path"}, "int"},
    {2, "futimes", {"int", "struct timeval *"}, {"fd", "tptr"}, "int"},
    {1, "getpgid", {"pid_t"}, {"pid"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "poll", {"struct pollfd *", "u_int", "int"}, {"fds", "nfds", "timeout"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {4, "__semctl", {"int", "int", "int", "union semun *"}, {"semid", "semnum", "cmd", "arg"}, "int"},
    {3, "semget", {"key_t", "int", "int"}, {"key", "nsems", "semflg"}, "int"},
    {3, "semop", {"int", "struct sembuf *", "size_t"}, {"semid", "sops", "nsops"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "msgctl", {"int", "int", "struct msqid_ds *"}, {"msqid", "cmd", "buf"}, "int"},
    {2, "msgget", {"key_t", "int"}, {"key", "msgflg"}, "int"},
    {4, "msgsnd", {"int", "const void *", "size_t", "int"}, {"msqid", "msgp", "msgsz", "msgflg"}, "int"},
    {5, "msgrcv", {"int", "void *", "size_t", "long", "int"}, {"msqid", "msgp", "msgsz", "msgtyp", "msgflg"}, "int"},
    {3, "shmat", {"int", "const void *", "int"}, {"shmid", "shmaddr", "shmflg"}, "int"},
    {3, "shmctl", {"int", "int", "struct shmid_ds *"}, {"shmid", "cmd", "buf"}, "int"},
    {1, "shmdt", {"const void *"}, {"shmaddr"}, "int"},
    {3, "shmget", {"key_t", "size_t", "int"}, {"key", "size", "shmflg"}, "int"},
    {2, "clock_gettime", {"clockid_t", "struct timespec *"}, {"clock_id", "tp"}, "int"},
    {2, "clock_settime", {"clockid_t", "const struct timespec *"}, {"clock_id", "tp"}, "int"},
    {2, "clock_getres", {"clockid_t", "struct timespec *"}, {"clock_id", "tp"}, "int"},
    {3, "ktimer_create", {"clockid_t", "struct sigevent *", "int *"}, {"clock_id", "evp", "timerid"}, "int"},
    {1, "ktimer_delete", {"int"}, {"timerid"}, "int"},
    {4, "ktimer_settime", {"int", "int", "const struct itimerspec *", "struct itimerspec *"}, {"timerid", "flags", "value", "ovalue"}, "int"},
    {2, "ktimer_gettime", {"int", "struct itimerspec *"}, {"timerid", "value"}, "int"},
    {1, "ktimer_getoverrun", {"int"}, {"timerid"}, "int"},
    {2, "nanosleep", {"const struct timespec *", "struct timespec *"}, {"rqtp", "rmtp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {1, "ntp_gettime", {"struct ntptimeval *"}, {"ntvp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "minherit", {"void *", "size_t", "int"}, {"addr", "len", "inherit"}, "int"},
    {1, "rfork", {"int"}, {"flags"}, "int"},
    {3, "openbsd_poll", {"struct pollfd *", "u_int", "int"}, {"fds", "nfds", "timeout"}, "int"},
    {0, "issetugid", {""}, {""}, "int"},
    {3, "lchown", {"char *", "int", "int"}, {"path", "uid", "gid"}, "int"},
    {1, "aio_read", {"struct aiocb *"}, {"aiocbp"}, "int"},
    {1, "aio_write", {"struct aiocb *"}, {"aiocbp"}, "int"},
    {4, "lio_listio", {"int", "struct aiocb *const *", "int", "struct sigevent *"}, {"mode", "acb_list", "nent", "sig"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {3, "getdents", {"int", "char *", "size_t"}, {"fd", "buf", "count"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {2, "lchmod", {"char *", "mode_t"}, {"path", "mode"}, "int"},
    {1, "netbsd_lchown", {"int"}, {"anom"}, "int"},
    {2, "lutimes", {"char *", "struct timeval *"}, {"path", "tptr"}, "int"},
    {1, "netbsd_msync", {"int"}, {"anom"}, "int"},
    {2, "nstat", {"char *", "struct nstat *"}, {"path", "ub"}, "int"},
    {2, "nfstat", {"int", "struct nstat *"}, {"fd", "sb"}, "int"},
    {2, "nlstat", {"char *", "struct nstat *"}, {"path", "ub"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {4, "preadv", {"int", "struct iovec *", "u_int", "off_t"}, {"fd", "iovp", "iovcnt", "offset"}, "int"},
    {4, "pwritev", {"int", "struct iovec *", "u_int", "off_t"}, {"fd", "iovp", "iovcnt", "offset"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "freebsd4_fhstatfs", {"const struct fhandle *", "struct ostatfs *"}, {"u_fhp", "buf"}, "int"},
    {2, "fhopen", {"const struct fhandle *", "int"}, {"u_fhp", "flags"}, "int"},
    {2, "fhstat", {"const struct fhandle *", "struct stat *"}, {"u_fhp", "sb"}, "int"},
    {1, "modnext", {"int"}, {"modid"}, "int"},
    {2, "modstat", {"int", "struct module_stat *"}, {"modid", "stat"}, "int"},
    {1, "modfnext", {"int"}, {"modid"}, "int"},
    {1, "modfind", {"const char *"}, {"name"}, "int"},
    {1, "kldload", {"const char *"}, {"file"}, "int"},
    {1, "kldunload", {"int"}, {"fileid"}, "int"},
    {1, "kldfind", {"const char *"}, {"file"}, "int"},
    {1, "kldnext", {"int"}, {"fileid"}, "int"},
    {2, "kldstat", {"int", "struct kld_file_stat *"}, {"fileid", "stat"}, "int"},
    {1, "kldfirstmod", {"int"}, {"fileid"}, "int"},
    {1, "getsid", {"pid_t"}, {"pid"}, "int"},
    {3, "setresuid", {"uid_t", "uid_t", "uid_t"}, {"ruid", "euid", "suid"}, "int"},
    {3, "setresgid", {"gid_t", "gid_t", "gid_t"}, {"rgid", "egid", "sgid"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "aio_return", {"struct aiocb *"}, {"aiocbp"}, "int"},
    {3, "aio_suspend", {"struct aiocb *const *", "int", "const struct timespec *"}, {"aiocbp", "nent", "timeout"}, "int"},
    {2, "aio_cancel", {"int", "struct aiocb *"}, {"fd", "aiocbp"}, "int"},
    {1, "aio_error", {"struct aiocb *"}, {"aiocbp"}, "int"},
    {1, "oaio_read", {"struct oaiocb *"}, {"aiocbp"}, "int"},
    {1, "oaio_write", {"struct oaiocb *"}, {"aiocbp"}, "int"},
    {4, "olio_listio", {"int", "struct oaiocb *const *", "int", "struct osigevent *"}, {"mode", "acb_list", "nent", "sig"}, "int"},
    {0, "yield", {""}, {""}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {1, "mlockall", {"int"}, {"how"}, "int"},
    {0, "munlockall", {""}, {""}, "int"},
    {2, "__getcwd", {"u_char *", "u_int"}, {"buf", "buflen"}, "int"},
    {2, "sched_setparam", {"pid_t", "const struct sched_param *"}, {"pid", "param"}, "int"},
    {2, "sched_getparam", {"pid_t", "struct sched_param *"}, {"pid", "param"}, "int"},
    {3, "sched_setscheduler", {"pid_t", "int", "const struct sched_param *"}, {"pid", "policy", "param"}, "int"},
    {1, "sched_getscheduler", {"pid_t"}, {"pid"}, "int"},
    {0, "sched_yield", {""}, {""}, "int"},
    {1, "sched_get_priority_max", {"int"}, {"policy"}, "int"},
    {1, "sched_get_priority_min", {"int"}, {"policy"}, "int"},
    {2, "sched_rr_get_interval", {"pid_t", "struct timespec *"}, {"pid", "interval"}, "int"},
    {2, "utrace", {"const void *", "size_t"}, {"addr", "len"}, "int"},
    {7, "freebsd4_sendfile", {"int", "int", "off_t", "size_t", "struct sf_hdtr *", "off_t *", "int"}, {"fd", "s", "offset", "nbytes", "hdtr", "sbytes", "flags"}, "int"},
    {3, "kldsym", {"int", "int", "void *"}, {"fileid", "cmd", "data"}, "int"},
    {1, "jail", {"struct jail *"}, {"jail"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "sigprocmask", {"int", "const sigset_t *", "sigset_t *"}, {"how", "set", "oset"}, "int"},
    {1, "sigsuspend", {"const sigset_t *"}, {"sigmask"}, "int"},
    {3, "freebsd4_sigaction", {"int", "const struct sigaction *", "struct sigaction *"}, {"sig", "act", "oact"}, "int"},
    {1, "sigpending", {"sigset_t *"}, {"set"}, "int"},
    {1, "freebsd4_sigreturn", {"const struct"}, {"ucontext4 * sigcntxp"}, "int"},
    {3, "sigtimedwait", {"const sigset_t *", "siginfo_t *", "const struct timespec *"}, {"set", "info", "timeout"}, "int"},
    {2, "sigwaitinfo", {"const sigset_t *", "siginfo_t *"}, {"set", "info"}, "int"},
    {3, "__acl_get_file", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {3, "__acl_set_file", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {3, "__acl_get_fd", {"int", "acl_type_t", "struct acl *"}, {"filedes", "type", "aclp"}, "int"},
    {3, "__acl_set_fd", {"int", "acl_type_t", "struct acl *"}, {"filedes", "type", "aclp"}, "int"},
    {2, "__acl_delete_file", {"const char *", "acl_type_t"}, {"path", "type"}, "int"},
    {2, "__acl_delete_fd", {"int", "acl_type_t"}, {"filedes", "type"}, "int"},
    {3, "__acl_aclcheck_file", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {3, "__acl_aclcheck_fd", {"int", "acl_type_t", "struct acl *"}, {"filedes", "type", "aclp"}, "int"},
    {5, "extattrctl", {"const char *", "int", "const char *", "int", "const char *"}, {"path", "cmd", "filename", "attrnamespace", "attrname"}, "int"},
    {5, "extattr_set_file", {"const char *", "int", "const char *", "void *", "size_t"}, {"path", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {5, "extattr_get_file", {"const char *", "int", "const char *", "void *", "size_t"}, {"path", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {3, "extattr_delete_file", {"const char *", "int", "const char *"}, {"path", "attrnamespace", "attrname"}, "int"},
    {2, "aio_waitcomplete", {"struct aiocb **", "struct timespec *"}, {"aiocbp", "timeout"}, "int"},
    {3, "getresuid", {"uid_t *", "uid_t *", "uid_t *"}, {"ruid", "euid", "suid"}, "int"},
    {3, "getresgid", {"gid_t *", "gid_t *", "gid_t *"}, {"rgid", "egid", "sgid"}, "int"},
    {0, "kqueue", {""}, {""}, "int"},
    {6, "kevent", {"int", "struct kevent *", "int", "struct kevent *", "int", "const struct timespec *"}, {"fd", "changelist", "nchanges", "eventlist", "nevents", "timeout"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {5, "extattr_set_fd", {"int", "int", "const char *", "void *", "size_t"}, {"fd", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {5, "extattr_get_fd", {"int", "int", "const char *", "void *", "size_t"}, {"fd", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {3, "extattr_delete_fd", {"int", "int", "const char *"}, {"fd", "attrnamespace", "attrname"}, "int"},
    {1, "__setugid", {"int"}, {"flag"}, "int"},
    {2, "nfsclnt", {"int", "caddr_t"}, {"flag", "argp"}, "int"},
    {2, "eaccess", {"char *", "int"}, {"path", "flags"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {3, "nmount", {"struct iovec *", "unsigned int", "int"}, {"iovp", "iovcnt", "flags"}, "int"},
    {0, "kse_exit", {""}, {""}, "int"},
    {1, "kse_wakeup", {"struct kse_mailbox *"}, {"mbx"}, "int"},
    {2, "kse_create", {"struct kse_mailbox *", "int"}, {"mbx", "newgroup"}, "int"},
    {3, "kse_thr_interrupt", {"struct kse_thr_mailbox *", "int", "long"}, {"tmbx", "cmd", "data"}, "int"},
    {1, "kse_release", {"struct timespec *"}, {"timeout"}, "int"},
    {1, "__mac_get_proc", {"struct mac *"}, {"mac_p"}, "int"},
    {1, "__mac_set_proc", {"struct mac *"}, {"mac_p"}, "int"},
    {2, "__mac_get_fd", {"int", "struct mac *"}, {"fd", "mac_p"}, "int"},
    {2, "__mac_get_file", {"const char *", "struct mac *"}, {"path_p", "mac_p"}, "int"},
    {2, "__mac_set_fd", {"int", "struct mac *"}, {"fd", "mac_p"}, "int"},
    {2, "__mac_set_file", {"const char *", "struct mac *"}, {"path_p", "mac_p"}, "int"},
    {4, "kenv", {"int", "const char *", "char *", "int"}, {"what", "name", "value", "len"}, "int"},
    {2, "lchflags", {"const char *", "int"}, {"path", "flags"}, "int"},
    {2, "uuidgen", {"struct uuid *", "int"}, {"store", "count"}, "int"},
    {7, "sendfile", {"int", "int", "off_t", "size_t", "struct sf_hdtr *", "off_t *", "int"}, {"fd", "s", "offset", "nbytes", "hdtr", "sbytes", "flags"}, "int"},
    {3, "mac_syscall", {"const char *", "int", "void *"}, {"policy", "call", "arg"}, "int"},
    {3, "getfsstat", {"struct statfs *", "long", "int"}, {"buf", "bufsize", "flags"}, "int"},
    {2, "statfs", {"char *", "struct statfs *"}, {"path", "buf"}, "int"},
    {2, "fstatfs", {"int", "struct statfs *"}, {"fd", "buf"}, "int"},
    {2, "fhstatfs", {"const struct fhandle *", "struct statfs *"}, {"u_fhp", "buf"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {1, "ksem_close", {"semid_t"}, {"id"}, "int"},
    {1, "ksem_post", {"semid_t"}, {"id"}, "int"},
    {1, "ksem_wait", {"semid_t"}, {"id"}, "int"},
    {1, "ksem_trywait", {"semid_t"}, {"id"}, "int"},
    {2, "ksem_init", {"semid_t *", "unsigned int"}, {"idp", "value"}, "int"},
    {5, "ksem_open", {"semid_t *", "const char *", "int", "mode_t", "unsigned int"}, {"idp", "name", "oflag", "mode", "value"}, "int"},
    {1, "ksem_unlink", {"const char *"}, {"name"}, "int"},
    {2, "ksem_getvalue", {"semid_t", "int *"}, {"id", "val"}, "int"},
    {1, "ksem_destroy", {"semid_t"}, {"id"}, "int"},
    {2, "__mac_get_pid", {"pid_t", "struct mac *"}, {"pid", "mac_p"}, "int"},
    {2, "__mac_get_link", {"const char *", "struct mac *"}, {"path_p", "mac_p"}, "int"},
    {2, "__mac_set_link", {"const char *", "struct mac *"}, {"path_p", "mac_p"}, "int"},
    {5, "extattr_set_link", {"const char *", "int", "const char *", "void *", "size_t"}, {"path", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {5, "extattr_get_link", {"const char *", "int", "const char *", "void *", "size_t"}, {"path", "attrnamespace", "attrname", "data", "nbytes"}, "int"},
    {3, "extattr_delete_link", {"const char *", "int", "const char *"}, {"path", "attrnamespace", "attrname"}, "int"},
    {4, "__mac_execve", {"char *", "char **", "char **", "struct mac *"}, {"fname", "argv", "envv", "mac_p"}, "int"},
    {3, "sigaction", {"int", "const struct sigaction *", "struct sigaction *"}, {"sig", "act", "oact"}, "int"},
    {1, "sigreturn", {"const struct __ucontext *"}, {"sigcntxp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {1, "getcontext", {"struct __ucontext *"}, {"ucp"}, "int"},
    {1, "setcontext", {"const struct __ucontext *"}, {"ucp"}, "int"},
    {2, "swapcontext", {"struct __ucontext *", "const struct __ucontext *"}, {"oucp", "ucp"}, "int"},
    {1, "swapoff", {"const char *"}, {"name"}, "int"},
    {3, "__acl_get_link", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {3, "__acl_set_link", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {2, "__acl_delete_link", {"const char *", "acl_type_t"}, {"path", "type"}, "int"},
    {3, "__acl_aclcheck_link", {"const char *", "acl_type_t", "struct acl *"}, {"path", "type", "aclp"}, "int"},
    {2, "sigwait", {"const sigset_t *", "int *"}, {"set", "sig"}, "int"},
    {3, "thr_create", {"ucontext_t *", "long *", "int"}, {"ctx", "id", "flags"}, "int"},
    {1, "thr_exit", {"long *"}, {"state"}, "int"},
    {1, "thr_self", {"long *"}, {"id"}, "int"},
    {2, "thr_kill", {"long", "int"}, {"id", "sig"}, "int"},
    {1, "_umtx_lock", {"struct umtx *"}, {"umtx"}, "int"},
    {1, "_umtx_unlock", {"struct umtx *"}, {"umtx"}, "int"},
    {1, "jail_attach", {"int"}, {"jid"}, "int"},
    {4, "extattr_list_fd", {"int", "int", "void *", "size_t"}, {"fd", "attrnamespace", "data", "nbytes"}, "int"},
    {4, "extattr_list_file", {"const char *", "int", "void *", "size_t"}, {"path", "attrnamespace", "data", "nbytes"}, "int"},
    {4, "extattr_list_link", {"const char *", "int", "void *", "size_t"}, {"path", "attrnamespace", "data", "nbytes"}, "int"},
    {2, "kse_switchin", {"struct kse_thr_mailbox *", "int"}, {"tmbx", "flags"}, "int"},
    {2, "ksem_timedwait", {"semid_t", "const struct timespec *"}, {"id", "abstime"}, "int"},
    {1, "thr_suspend", {"const struct timespec *"}, {"timeout"}, "int"},
    {1, "thr_wake", {"long"}, {"id"}, "int"},
    {2, "kldunloadf", {"int", "int"}, {"fileid", "flags"}, "int"},
    {2, "audit", {"const void *", "u_int"}, {"record", "length"}, "int"},
    {3, "auditon", {"int", "void *", "u_int"}, {"cmd", "data", "length"}, "int"},
    {1, "getauid", {"uid_t *"}, {"auid"}, "int"},
    {1, "setauid", {"uid_t *"}, {"auid"}, "int"},
    {1, "getaudit", {"struct auditinfo *"}, {"auditinfo"}, "int"},
    {1, "setaudit", {"struct auditinfo *"}, {"auditinfo"}, "int"},
    {2, "getaudit_addr", {"struct auditinfo_addr *", "u_int"}, {"auditinfo_addr", "length"}, "int"},
    {2, "setaudit_addr", {"struct auditinfo_addr *", "u_int"}, {"auditinfo_addr", "length"}, "int"},
    {1, "auditctl", {"char *"}, {"path"}, "int"},
    {5, "_umtx_op", {"void *", "int", "u_long", "void *", "void *"}, {"obj", "op", "val", "uaddr1", "uaddr2"}, "int"},
    {2, "thr_new", {"struct thr_param *", "int"}, {"param", "param_size"}, "int"},
    {3, "sigqueue", {"pid_t", "int", "void *"}, {"pid", "signum", "value"}, "int"},
    {4, "kmq_open", {"const char *", "int", "mode_t", "const struct mq_attr *"}, {"path", "flags", "mode", "attr"}, "int"},
    {3, "kmq_setattr", {"int", "const struct mq_attr *", "struct mq_attr *"}, {"mqd", "attr", "oattr"}, "int"},
    {5, "kmq_timedreceive", {"int", "char *", "size_t", "unsigned *", "const struct timespec *"}, {"mqd", "msg_ptr", "msg_len", "msg_prio", "abs_timeout"}, "int"},
    {5, "kmq_timedsend", {"int", "const char *", "size_t", "unsigned", "const struct timespec *"}, {"mqd", "msg_ptr", "msg_len", "msg_prio", "abs_timeout"}, "int"},
    {2, "kmq_notify", {"int", "const struct sigevent *"}, {"mqd", "sigev"}, "int"},
    {1, "kmq_unlink", {"const char *"}, {"path"}, "int"},
    {3, "abort2", {"const char *", "int", "void **"}, {"why", "nargs", "args"}, "int"},
    {2, "thr_set_name", {"long", "const char *"}, {"id", "name"}, "int"},
    {2, "aio_fsync", {"int", "struct aiocb *"}, {"op", "aiocbp"}, "int"},
    {3, "rtprio_thread", {"int", "lwpid_t", "struct rtprio *"}, {"function", "lwpid", "rtp"}, "int"},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {0, NULL, {""}, {""}, NULL},
    {2, "sctp_peeloff", {"int", "_t"}, {"sd", "name"}, "int"},
    {7, "sctp_generic_sendmsg", {"int", "caddr_t", "int", "caddr_t", "__socklen_t", "struct sctp_sndrcvinfo *", "int"}, {"sd", "msg", "mlen", "to", "tolen", "sinfo", "flags"}, "int"},
    {7, "sctp_generic_sendmsg_iov", {"int", "struct iovec *", "int", "caddr_t", "__socklen_t", "struct sctp_sndrcvinfo *", "int"}, {"sd", "iov", "iovlen", "to", "tolen", "sinfo", "flags"}, "int"},
    {7, "sctp_generic_recvmsg", {"int", "struct iovec *", "int", "struct sockaddr *", "__socklen_t *", "struct sctp_sndrcvinfo *", "int *"}, {"sd", "iov", "iovlen", "from", "fromlenaddr", "sinfo", "msg_flags"}, "int"},
    {4, "pread", {"int", "void *", "size_t", "off_t"}, {"fd", "buf", "nbyte", "offset"}, "int"},
    {4, "pwrite", {"int", "const void *", "size_t", "off_t"}, {"fd", "buf", "nbyte", "offset"}, "int"},
    {6, "mmap", {"caddr_t", "size_t", "int", "int", "int", "off_t"}, {"addr", "len", "prot", "flags", "fd", "pos"}, "int"},
    {3, "lseek", {"int", "off_t", "int"}, {"fd", "offset", "whence"}, "int"},
    {2, "truncate", {"char *", "off_t"}, {"path", "length"}, "int"},
    {2, "ftruncate", {"int", "off_t"}, {"fd", "length"}, "int"},
    {3, "thr_kill2", {"pid_t", "long", "int"}, {"pid", "id", "sig"}, "int"},
    {1, "MAXSYSCALL", {"int"}, {"anom"}, "int"}
  };
